export const ADD_LIST = "ADD_LIST";
export const EDIT_LIST = "EDIT_LIST";
export const REMOVE_LIST = "REMOVE_LIST";
export const FETCH_LISTS_START = "FETCH_LISTS_START";
export const FETCH_LISTS_SUCCESS = "FETCH_LISTS_SUCCESS";
export const FETCH_LISTS_FAIL = "FETCH_LISTS_FAIL";

export const ADD_TASK = "ADD_TASK";
export const TOGGLE_TASK_SELECTION = "TOGGLE_TASK_SELECTION";
export const EDIT_TASK = "EDIT_TASK";
export const REMOVE_TASK = "REMOVE_TASK";
